name: pywatershed
channels:
  - conda-forge
  - nodefaults
  - pyviz
  - bioconda
dependencies:
  - epiweeks  
  - netCDF4
  - networkx
  - numpy
  - numba
  - pandas>=1.4.0
  - pint
  - pip
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - pyyaml
  - cartopy
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - bash_kernel
  - git
  - ipython
  - jupyter
  - jupyterlab
  - nbconvert
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pydot
  - shapely<2.0.0
  - filelock
  - pip:
      - click != 8.1.0
      - black
      - isort
      - flake8
      - pylint
      - git+https://github.com/modflowpy/flopy.git
      - modflow-devtools
      - git+https://github.com/pydata/xarray.git
