[pytest]
markers =
    domainless: tests not requiring input from domain files
    domain: tests requiring input from domain files
filterwarnings =
    ignore:.*is not an available control option:UserWarning
    ignore:No output variables found for process.*:UserWarning
    ignore:.*has no restart variables to read or write.*:UserWarning
