name: pynhm
channels:
  - conda-forge
  - nodefaults
  - bioconda
dependencies:
  - epiweeks
  - netCDF4
  - networkx
  - numpy
  - numba
  - pandas
  - pip
  - pip:
      - click != 8.1.0
      - black < 23.1.0
      - isort
      - flake8
      - pylint
      - git+https://github.com/modflowpy/flopy.git
      - modflow-devtools
      - git+https://github.com/jmccreight/xarray.git@to_dict-numpy-data-version-fake
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - pyyaml
  - flopy
