name: pynhm-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - netCDF4
  - networkx
  - numpy
  - numba
  - pandas
  - pip
  - pip:
      - click != 8.1.0
      - black < 23.1.0
      - isort
      - flake8
      - pylint
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - pyyaml
  - xarray
  - flopy
