name: pyws
channels:
  - conda-forge
  - nodefaults
  - bioconda
dependencies:
  - epiweeks
  - netCDF4
  - networkx
  - numpy
  - numba
  - pandas
  - pint
  - pip
  - pip:
      - black
      - isort
      - flake8
      - pylint
      - git+https://github.com/modflowpy/flopy.git
      - modflow-devtools
      - git+https://github.com/pydata/xarray.git
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - pyyaml
  - flopy
