name: pynhm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - netCDF4
  - networkx
  - numpy
  - numba
  - pandas
  - pip
  - pip:
      - click != 8.1.0
      - black < 23.1.0
      - isort
      - flake8
      - pylint
      - "--editable=git+https://github.com/modflowpy/flopy.git#egg=flopy"
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - pyyaml
  - xarray
  - flopy
