name: example notebooks test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  test:
    name: ${{ matrix.os}} py${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Set environment variables
        run: |
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: examples/examples_env.yml
          environment-name: pynhm_nb
          cache-env: true
          #cache-env-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}"
          
      - name: Install error reporter
        run: |
          python -m pip install pytest-github-actions-annotate-failures
          
      - name: Install dependencies and this package
        run: |
          # python -m pip install wheel
          python -m pip install .

      - name: Version info
        run: |
          conda info -a
          conda list
          python -m pip -V
          python -m pip list

      - name: Import pynhm
        run: |
          python -c "import pynhm"
          
      - name: Run tests
        working-directory: autotest_exs
        run: python -m pytest -s -vv
          --durations=0

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results for examples-${{ runner.os }}-${{ matrix.python-version }}
          path: ./autotest_exs/pytest.xml
